name: Phoenix House Calendar Sync

on:
  schedule:
    - cron: '0 3 * * *'  # runs daily at 3AM UTC
  workflow_dispatch:  # allows you to manually trigger anytime

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download latest calendar from Google Drive
      run: |
        curl -L "https://drive.google.com/uc?export=download&id=1LBxChOu4hxx0lpzeIuOQG2JvRdJbNrhn" -o Phoenix_House_Master_Events_2025.ics

    - name: Commit and push updated calendar file
      run: |
        git config --local user.name "Phoenix House Bot"
        git config --local user.email "automation@phoenixhouse.com"
        git add Phoenix_House_Master_Events_2025.ics
        git commit -m "Automated calendar update" || echo "No changes to commit"
        git push https://${{ secrets.GH_PAT }}@github.com/bit901/phoenix-dance-events.git HEAD:main
